spring:
#链接mysql数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  #配置JPA显示sql方便调试
  jpa:
    show-sql: true
    #格式化显示的SQL语句
    properties:
      hibernate:
        format_sql: true
#打印sql语句中传入的参数值
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
